%% Test real CRT pre-readout-post module construction
N=128;
radius=25;
theta=(0:N-1).'*2*pi/N;
k=[radius*cos(theta) radius*sin(theta)];
gammaBar=42.5774789e6;
dt=5e-6;
G=[diff(k,1,1);k(1,:)-k(end,:)]/(gammaBar*dt);

result=struct();
result.G=G;
result.S=diff([G;G(1,:)],1,1)/dt;
result.ktraj_actual=k;
result.ktraj_target=k;
result.time_grad=(0:N-1).'*dt;
result.opts=struct('gammaBar',gammaBar,'dtGrad',dt,'dtADC',dt, ...
    'nADC',N,'Guse',19e-3,'Suse',171);

result=add_pre_gradient_to_periodic_result(result,[]);
result=add_post_gradient_to_periodic_result(result,[]);

assert(isfield(result,'post'));
assert(isfield(result.post,'ktraj_actual'));
assert(norm(result.post.startG-G(end,:))<1e-10);
assert(norm(result.post.endG)<1e-10);
assert(result.post.returnErrorNorm<1e-6);
assert(norm(result.post.ktraj_actual(end,:))<1e-6);
assert(result.sequence.adcStartIndex==result.pre.Npre+1);
assert(result.sequence.postStartIndex==result.pre.Npre+N+1);
assert(all(result.sequence.adcMask(1:result.pre.Npre)==0));
assert(all(result.sequence.adcMask(result.sequence.adcStartIndex: ...
    result.sequence.adcEndIndex)==1));
assert(all(result.sequence.adcMask(result.sequence.postStartIndex:end)==0));
assert(norm(result.sequence.ktraj_actual(end,:))<1e-6);

% The displayed/saved complete trajectory must be generated by one
% continuous reintegration of the complete waveform. It must not be a
% concatenation of pre.ktraj_actual, result.ktraj_actual and
% post.ktraj_actual, which use different local origins/time conventions.
kExpected = integrate_gradient(result.sequence.G,result.opts,zeros(1,2));
assert(max(abs(result.sequence.ktraj_actual(:)-kExpected(:)))<1e-12);
assert(norm(result.sequence.returnError-kExpected(end,:))<1e-12);
assert(result.sequence.readoutClosureIndex==result.sequence.postStartIndex);
assert(norm(result.sequence.readoutClosurePoint- ...
    result.sequence.ktraj_actual(result.sequence.postStartIndex,:))<1e-12);
assert(norm(result.sequence.readoutClosurePoint- ...
    result.sequence.ktraj_actual(result.sequence.adcStartIndex,:))<1e-6);

% Deliberately corrupt the segment-local trajectory caches and rebuild. The
% complete trajectory must remain unchanged because sequence.G is the sole
% source of truth.
kReference = result.sequence.ktraj_actual;
result.pre.ktraj_actual(:) = 123;
result.post.ktraj_actual(:) = -456;
result = add_post_gradient_to_periodic_result(result,result.post.Npost);
assert(max(abs(result.sequence.ktraj_actual(:)-kReference(:)))<1e-6);

% The expanded full-FID module follows the same continuous convention and
% includes an explicit ring-to-post closure point.
full = expand_periodic_readout(result,8);
kFullExpected = integrate_gradient(full.G_with_module,result.opts,zeros(1,2));
assert(max(abs(full.ktraj_with_module(:)-kFullExpected(:)))<1e-12);
assert(norm(full.returnError-kFullExpected(end,:))<1e-12);
assert(full.readoutClosureIndex==full.postStartIndex);
assert(norm(full.readoutClosurePoint- ...
    full.ktraj_with_module(full.postStartIndex,:))<1e-12);
if exist('quadprog','file')==2
    assert(result.pre.isFeasible);
    assert(result.post.isFeasible);
    assert(result.sequence.isFeasible);
end
disp('test_crt_complete_module passed.');
